# Generated by Django 4.0.3 on 2022-03-04 15:06

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.upload_func)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent', models.BooleanField(default=False)),
                ('send_attempt_over', models.BooleanField(default=False)),
            ],
        ),
    ]
