# Generated by Django 4.0 on 2021-12-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
