# Generated by Django 4.0.3 on 2022-03-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_letter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
