# Generated by Django 4.0.3 on 2022-03-03 20:36

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_letter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_func),
        ),
    ]
